"""Events table

Revision ID: 445236298d1d
Revises: e6bb85cdeda4
Create Date: 2025-02-22 21:18:57.965831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445236298d1d'
down_revision = 'e6bb85cdeda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
