"""Create registrations table


Revision ID: e3bba1c59f63
Revises: 7fe5a1111a0b
Create Date: 2025-02-26 16:04:18.493360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bba1c59f63'
down_revision = '7fe5a1111a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('carer_first_name', sa.String(length=50), nullable=True),
    sa.Column('carer_last_name', sa.String(length=50), nullable=True),
    sa.Column('carer_email', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address_line1', sa.String(length=100), nullable=False),
    sa.Column('address_line2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('postcode', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('level_of_study', sa.String(length=50), nullable=False),
    sa.Column('subject_area', sa.String(length=100), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('marketing_sources', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    # ### end Alembic commands ###
